# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-23 15:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='link',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
